# Generated by Django 5.2 on 2025-04-27 07:41

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Monthly', 'Monthly'), ('Three Months', 'Three Months'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], default='Monthly', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fitness_classes_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('plans', models.ManyToManyField(related_name='fitness_classes', to='plans.plans')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduled_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('instructor', models.CharField(max_length=50)),
                ('total_seats', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField()),
                ('present_students', models.PositiveIntegerField(default=0)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.fitness_classes_category')),
            ],
            options={
                'unique_together': {('fitness_class', 'date_time')},
            },
        ),
    ]
