# Generated by Django 5.2 on 2025-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
