# Generated by Django 5.2 on 2025-05-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plans_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='type',
            field=models.CharField(default='Monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduled_classes',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
